import type { ReactNode } from "react";
import "./globals.css";

export const metadata = {
  title: "Your Site",
  description: "Generated by the website-scaffold skill",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
